### ISSUE TITLE
采用最新的AndroidStudio编译报错：Expected caller to ensure valid ABI: MIPS

### ISSUE THREAD

**Issue by cxyzy1** [kevin-nazgul/olog#1]
采用最新的AndroidStudio编译报错：Expected caller to ensure valid ABI: MIPS
AndroidStudio版本：3.2.1
NDK：18.1.5063045

**Comment by kevin-nazgul** [comment]
已修复 #f99030c

**Comment by cxyzy1** [comment]
速度很快，👍，可以编译了

**Comment by ArcherYL** [comment]
能告诉我怎么修复的吗，我项目也出现了一样的问题

**Comment by kevin-nazgul** [comment]
最新版本的ndk去除了MIPS的编译工具，升级到最新的gradle版本可以解决，具体见这个issue的修改。

ArcherYL <notifications@github.com> 于 2018年11月17日周六 22:18写道：
